// Itens de referência e armas extras, escritos à mão (o gerarConteudo.mjs transforma em JSON).
// Referências a jogos, animes, filmes e séries — os nomes são homenagens, não os originais.

// ---------- 60 itens de referência ----------
// [id, nome, descrição, ícone, cor, raridade, efeito, etiquetas]
export const REFERENCIAS = [
  // --- jogos ---
  ['cogumelo_vermelho', 'Cogumelo Vermelho', '+25 chama máx e balas maiores. Você cresceu!', 'cogumelo', '#e2452b', 2, { stats: { chamaMax: 25 }, mods: { tamanho: 1.2 } }, ['terra', 'coracao']],
  ['cogumelo_verde', 'Cogumelo Verde', '+40 chama máx. Uma vida extra, quase.', 'cogumelo', '#7fdc8a', 3, { stats: { chamaMax: 40 } }, ['coracao', 'sorte']],
  ['estrela_piscante', 'Estrela Piscante', '+15% velocidade, esquiva perfeita fácil, chama dourada.', 'estrela', '#ffd23f', 3, { stats: { velocidade: 1.15, raioEsquiva: 4 }, visual: { chama: 'dourada' } }, ['vento', 'luz']],
  ['triangulo_dourado', 'Triângulo Dourado', '+10% dano, +10% velocidade, +10 chama máx.', 'triangulo', '#ffd23f', 3, { stats: { dano: 1.1, velocidade: 1.1, chamaMax: 10 } }, ['ouro', 'luz']],
  ['recipiente_coracao', 'Recipiente de Coração', '+20 chama máx.', 'coracao', '#ff5a8a', 1, { stats: { chamaMax: 20 } }, ['coracao']],
  ['frasco_estus', 'Frasco de Estus', '+5 de chama a cada sala limpa.', 'frasco', '#ff9a2e', 2, { stats: { curaSala: 5 } }, ['frasco', 'fogo']],
  ['fogueira', 'Fogueira Acesa', 'A chama queima 20% mais devagar. Descanse aqui.', 'chama', '#ff7a2e', 2, { stats: { decaimento: 0.8 } }, ['fogo', 'vela']],
  ['argola_dourada', 'Argola Dourada', '+15% velocidade e puxa a cera de longe.', 'anel', '#ffd23f', 2, { stats: { velocidade: 1.15, ima: 0.5 } }, ['anel', 'vento']],
  ['cubo_companheiro', 'Cubo Companheiro', 'Um cubinho fiel gira em volta e bloqueia balas.', 'cubo', '#ff8ac8', 2, { especial: 'orbe' }, ['cristal']],
  ['bolo_mentira', 'O Bolo é uma Mentira', '+40 chama máx, mas ela queima 30% mais rápido.', 'bolo', '#c86bff', 2, { stats: { chamaMax: 40, decaimento: 1.3 }, maldito: true }, ['coracao']],
  ['pe_de_cabra', 'Pé de Cabra do Cientista', 'Monstros que encostam em você levam dano.', 'osso', '#ff9a2e', 1, { stats: { espinhos: 4 } }, ['osso', 'terra']],
  ['pastilha_poder', 'Pastilha de Poder', 'Encostar machuca os monstros. +8% velocidade.', 'orbe', '#ffd23f', 2, { stats: { espinhos: 6, velocidade: 1.08 } }, ['ouro']],
  ['d20', 'Dado de Vinte Lados', '+8% crítico. Tirou 20!', 'dado', '#c86bff', 2, { stats: { critico: 0.08 } }, ['dado', 'sorte']],
  ['pocao_mana', 'Poção de Mana', 'Atira 12% mais rápido. Chama azul.', 'frasco', '#4f9dff', 2, { stats: { cadencia: 0.88 }, visual: { chama: 'azul' } }, ['frasco', 'eco']],
  ['pocao_vida', 'Poção de Vida', '+15 chama máx e enche a chama.', 'frasco', '#e2452b', 1, { stats: { chamaMax: 15 }, especial: 'cura' }, ['frasco', 'sangue']],
  ['moeda_encanador', 'Moeda do Encanador', '+20% cera.', 'moeda', '#ffd23f', 1, { stats: { ceraBonus: 1.2 } }, ['moeda', 'ouro']],
  ['elmo_espartano', 'Elmo Verde Espartano', 'Um escudo por sala e -15% de dano recebido.', 'mascara', '#4a8a3a', 3, { stats: { danoRecebido: 0.85 }, especial: 'escudo' }, ['capa', 'terra']],
  ['bichinho_virtual', 'Bichinho Virtual', 'Uma velinha de estimação atira junto com você.', 'gemea', '#ff8ac8', 3, { especial: 'gemea' }, ['vela']],
  ['cartucho_assoprado', 'Cartucho Assoprado', 'Recarga 25% mais rápida. Era só assoprar.', 'pente', '#7d8494', 1, { stats: { recarga: 0.75 } }, ['pergaminho']],
  ['codigo_secreto', 'Código Secreto', 'Cima, cima, baixo, baixo... +30 chama máx e +1 dash.', 'pergaminho', '#ffd23f', 3, { stats: { chamaMax: 30, dashes: 1 } }, ['pergaminho', 'sorte']],
  ['gorro_heroi', 'Gorro do Herói', '+15% alcance e balas que perseguem.', 'chapeu', '#4a8a3a', 2, { stats: { alcance: 1.15 }, mods: { teleguiado: 0.6 } }, ['olhar']],
  // --- animes ---
  ['esfera_estrelas', 'Esfera de Quatro Estrelas', '+1 sorte e +25% cera. Faltam seis.', 'esfera', '#ff9a2e', 2, { stats: { sorte: 1, ceraBonus: 1.25 } }, ['sorte', 'ouro']],
  ['semente_deuses', 'Semente dos Deuses', 'Enche a chama e dá +10 chama máx.', 'lagrima', '#7fdc8a', 1, { stats: { chamaMax: 10 }, especial: 'cura' }, ['terra']],
  ['chapeu_palha', 'Chapéu de Palha', '+1 sorte e +8% velocidade. Vou ser o rei!', 'chapeu_palha', '#ffd23f', 2, { stats: { sorte: 1, velocidade: 1.08 } }, ['sorte', 'vento']],
  ['caderno_morte', 'Caderno da Morte', '+40% dano, mas a chama queima 25% mais rápido.', 'livro', '#2a2033', 3, { stats: { dano: 1.4, decaimento: 1.25 }, maldito: true }, ['sombra', 'pergaminho']],
  ['bandana_ninja', 'Bandana da Vila Oculta', 'Clones das sombras: +1 tiro.', 'bandana', '#4f9dff', 3, { mods: { multiplos: 1 } }, ['eco']],
  ['olho_copiador', 'Olho Vermelho Copiador', 'Balas perseguem e a esquiva perfeita fica fácil.', 'olho', '#e2452b', 3, { stats: { raioEsquiva: 2 }, mods: { teleguiado: 1 } }, ['olho', 'olhar']],
  ['mascara_pedra', 'Máscara de Pedra', 'Abates curam 1, mas -20% luz. Vampirismo.', 'mascara', '#a0784a', 2, { stats: { roubaVida: 1, luz: 0.8 }, maldito: true }, ['mascara', 'sangue']],
  ['capa_tropa', 'Capa da Tropa de Exploração', '+1 dash e +10% velocidade.', 'capa', '#4a8a3a', 2, { stats: { dashes: 1, velocidade: 1.1 } }, ['capa', 'vento']],
  ['pedra_filosofal', 'Pedra Filosofal', '+30% cera e abates curam 0.5.', 'cristal', '#e2452b', 3, { stats: { ceraBonus: 1.3, roubaVida: 0.5 } }, ['cristal', 'sangue']],
  ['oculos_irmao', 'Óculos do Grande Irmão', '+15% dano e balas maiores. Quem você pensa que eu sou?', 'oculos', '#ff5a2e', 2, { stats: { dano: 1.15 }, mods: { tamanho: 1.15 }, visual: { acessorio: 'oculos_grandes' } }, ['lente']],
  ['ramen', 'Ramen Quentinho', '+4 de chama a cada sala limpa.', 'xicara', '#ffb43a', 1, { stats: { curaSala: 4 } }, ['frasco']],
  ['caderno_alquimista', 'Luva de Círculo Alquímico', 'Balas incendeiam e explodem de leve.', 'mao', '#e2452b', 2, { mods: { queima: true, explosao: 6 } }, ['luva', 'fogo']],
  // --- filmes ---
  ['um_anel', 'O Um Anel', 'Balas atravessam paredes e você some... mas leva +20% de dano.', 'anel', '#ffd23f', 3, { stats: { danoRecebido: 1.2 }, mods: { espectral: true }, visual: { acessorio: 'lencol' }, maldito: true }, ['anel', 'sombra']],
  ['capa_invisivel', 'Capa da Invisibilidade', 'Esquiva perfeita fácil e +5% crítico.', 'capa', '#b8b0d0', 2, { stats: { raioEsquiva: 4, critico: 0.05 }, visual: { acessorio: 'lencol' } }, ['capa', 'sombra']],
  ['vira_tempo', 'Vira-Tempo', 'Dash volta 25% antes e a câmera lenta dura mais.', 'ampulheta', '#ffd23f', 2, { stats: { cooldownDash: 0.75, lentoExtra: 1.4 } }, ['relogio', 'tempo']],
  ['pilula_vermelha', 'Pílula Vermelha', 'Câmera lenta 50% maior e esquiva fácil. Veja o código.', 'pilula', '#e2452b', 2, { stats: { lentoExtra: 1.5, raioEsquiva: 3 } }, ['tempo', 'sombra']],
  ['pilula_azul', 'Pílula Azul', '+4 chama por sala e a chama dura mais. Ignorância é uma bênção.', 'pilula', '#4f9dff', 1, { stats: { curaSala: 4, decaimento: 0.9 } }, ['luz']],
  ['toalha', 'Toalha do Mochileiro', 'Não entre em pânico: -10% dano recebido e +0.42 sorte.', 'capa', '#7fd7ff', 1, { stats: { danoRecebido: 0.9, sorte: 0.42 } }, ['capa', 'sorte']],
  ['pato_borracha', 'Pato de Borracha', '+5% crítico e +0.5 sorte. Ele escuta seus problemas.', 'pato', '#ffd23f', 1, { stats: { critico: 0.05, sorte: 0.5 } }, ['sorte']],
  ['espinafre', 'Lata de Espinafre', '+15% dano e +30% empurrão.', 'barril', '#4a8a3a', 2, { stats: { dano: 1.15, empurrao: 1.3 } }, ['terra']],
  ['bigorna', 'Bigorna de Desenho Animado', 'Balas enormes e pesadas, mas mais lentas.', 'pedra', '#7d8494', 2, { stats: { empurrao: 1.5 }, mods: { tamanho: 1.4, velBala: 0.85 } }, ['pedra', 'terra']],
  ['caixa_pandora', 'Caixa de Pandora', '+35% dano e +1 sorte, mas monstros têm +20% vida.', 'cubo', '#c86bff', 3, { stats: { dano: 1.35, sorte: 1, vidaInimigos: 1.2 }, maldito: true }, ['sombra']],
  ['calice', 'Cálice Sagrado', 'Abates curam 0.6 e a cera cura +20%. Escolheu bem.', 'votiva', '#ffd23f', 3, { stats: { roubaVida: 0.6, curaCera: 1.2 } }, ['ouro', 'luz']],
  ['chapeu_arqueologo', 'Chapéu do Arqueólogo', '+1 sorte. Tesouros aparecem mais.', 'chapeu', '#8a5a2b', 2, { stats: { sorte: 1 } }, ['sorte']],
  ['cristal_sabre', 'Cristal de Sabre', 'Balas atravessam 2 monstros.', 'cristal', '#4f9dff', 2, { mods: { perfura: 2 } }, ['cristal', 'lamina']],
  ['elmo_beskar', 'Elmo de Beskar', '-15% dano recebido. Este é o caminho.', 'mascara', '#cfd8dc', 2, { stats: { danoRecebido: 0.85 } }, ['mascara', 'terra']],
  ['reator_peito', 'Reator no Peito', '+20 chama máx e raio que pula 1x.', 'orbe', '#7fe8ff', 3, { stats: { chamaMax: 20 }, mods: { eletrico: 1 } }, ['coracao', 'raio']],
  ['escudo_estrelado', 'Escudo Redondo Estrelado', 'Um escudo por sala, e as balas voltam como bumerangue.', 'escudo', '#4f9dff', 3, { mods: { bumerangue: true }, especial: 'escudo' }, ['capa']],
  ['anel_juramento', 'Anel do Juramento Verde', '+12% dano e chama verde. Na noite mais densa...', 'anel', '#7fdc8a', 2, { stats: { dano: 1.12 }, visual: { chama: 'verde' } }, ['anel', 'luz']],
  ['cinto_utilidades', 'Cinto de Utilidades', '+30% pente e recarga 20% mais rápida.', 'pente', '#ffd23f', 2, { stats: { pente: 1.3, recarga: 0.8 } }, ['pergaminho']],
  ['cartucho_teia', 'Cartucho de Teia', '15% de chance de grudar (congelar) o monstro.', 'frasco', '#cfd8dc', 1, { mods: { congela: 0.15 } }, ['mola']],
  // --- séries ---
  ['rosquinha', 'Rosquinha Rosa', '+15 chama máx, -5% velocidade. Hmmm...', 'rosquinha', '#ff8ac8', 1, { stats: { chamaMax: 15, velocidade: 0.95 } }, ['coracao']],
  ['cabine_azul', 'Cabine Azul de Bolso', 'Maior por dentro: +40% pente e +15% alcance.', 'cubo', '#2a4fd0', 2, { stats: { pente: 1.4, alcance: 1.15 } }, ['tempo']],
  ['pisca_pisca', 'Pisca-Pisca de Natal', '+40% luz. Alguém está tentando falar com você.', 'lamparina', '#ff5a8a', 1, { stats: { luz: 1.4 } }, ['luz']],
  ['cristal_azul', 'Cristal Azul', 'Atira 25% mais rápido, mas a chama queima 20% mais.', 'cristal', '#7fd7ff', 2, { stats: { cadencia: 0.75, decaimento: 1.2 }, maldito: true }, ['vidro']],
  ['ovo_dragao', 'Ovo de Dragão', 'Balas incendeiam e +10 chama máx.', 'esfera', '#a0303a', 2, { stats: { chamaMax: 10 }, mods: { queima: true } }, ['fogo']],
  ['medalhao_bruxo', 'Medalhão do Bruxo', '+5% crítico e balas que perseguem um pouco.', 'amuleto', '#cfd8dc', 2, { stats: { critico: 0.05 }, mods: { teleguiado: 0.4 } }, ['amuleto', 'olhar']],
  ['cafe_danado', 'Café Danado de Bom', 'Atira 12% mais rápido.', 'xicara', '#8a5a2b', 1, { stats: { cadencia: 0.88 } }, ['eco']],
  ['bola_volei', 'Bola de Vôlei Amiga', 'Uma amiga redonda gira em volta e bloqueia balas.', 'esfera', '#f4ead6', 2, { especial: 'orbe' }, ['sorte']],
];

// ---------- 50 armas extras (por raridade: 1 comum · 2 incomum · 3 rara · 4 épica · 5 mítica) ----------
// [id, nome, descrição, raridade, molde (arma de onde vêm os valores e o desenho), cor do desenho, bala, cor da bala, som, mudanças]
export const ARMAS = [
  // --- MÍTICAS ---
  ['tete', 'TETE', 'O pug lendário. Late tão alto que os latidos perseguem, atravessam e explodem.', 5, 'tete', null, 'latido', '#ffd23f', 'latido',
    { dano: 3.5, cadencia: 0.16, pente: 24, recarga: 0.7, projeteis: 3, dispersao: 24, velocidade: 230, alcance: 260, municao: -1, recuo: 20, empurrao: 240, tremor: 0.006, teleguiado: 1.4, perfura: 3, explosao: 12 }],
  ['genki_dama', 'Bomba de Energia Coletiva', 'Junta a energia de todos: uma esfera gigante e lenta que apaga a sala.', 5, 'vazio', '#7fe8ff', 'orbe', '#7fe8ff', 'vazio',
    { dano: 30, cadencia: 1.6, pente: 3, recarga: 2.4, velocidade: 70, alcance: 300, municao: 18, explosao: 60, perfura: 99, tamanho: 2.2 }],
  ['bfg', 'BFG de Cera', 'A Grande Arma. Uma bola verde que eletrocuta tudo no caminho e explode.', 5, 'lancador', '#7fdc8a', 'orbe', '#7fff4f', 'vazio',
    { dano: 20, cadencia: 1.3, pente: 4, recarga: 2, velocidade: 110, alcance: 280, municao: 24, explosao: 50, eletrico: 4 }],
  ['nix', 'NIX', 'A gata preta. Miados de sombra que atravessam paredes, perseguem e dão choque.', 5, 'nix', null, 'miau', '#b06bff', 'miau',
    { dano: 3, cadencia: 0.2, pente: 18, recarga: 0.7, projeteis: 2, dispersao: 16, velocidade: 220, alcance: 280, municao: -1, recuo: 10, empurrao: 120, tremor: 0.004, espectral: true, teleguiado: 2, perfura: 2, eletrico: 2 }],
  ['yuumi', 'YUUMI', 'A gata tigrada cinza de patinhas brancas. Miados que quicam pela sala e viram novelos explosivos.', 5, 'yuumi', null, 'miau', '#d8d2c4', 'miau',
    { dano: 3.2, cadencia: 0.18, pente: 20, recarga: 0.7, projeteis: 2, dispersao: 20, velocidade: 240, alcance: 300, municao: -1, recuo: 10, empurrao: 140, tremor: 0.004, ricochete: 3, fragmenta: 3, fragmentoExplode: true, explosao: 8 }],
  // exclusiva da Ana: a câmera com a foto do Luiz
  ['polaroid_luiz', 'Polaroid do Luiz', 'Clique! O flash atordoa e atravessa. Sai uma foto do Luiz a cada tiro.', 4, 'polaroid_luiz', null, 'bala_grande', '#ffffff', 'zap',
    { dano: 3.4, cadencia: 0.32, pente: 10, recarga: 0.9, projeteis: 1, dispersao: 2, velocidade: 300, alcance: 220, municao: -1, recuo: 10, empurrao: 90, tremor: 0.003, perfura: 3, congela: 0.4, tamanho: 1.5, exclusivo: 'ana' }],
  // --- ÉPICAS ---
  ['kame', 'Onda Kame', 'Junta as mãos e solta um raio de energia azul que atravessa tudo.', 4, 'laser', '#4f9dff', 'laser', '#7fd7ff', 'laser', { dano: 6, cadencia: 0.5, pente: 8, laser: true, tamanho: 2.2, alcance: 320, municao: 64 }],
  ['agulhador', 'Agulhador Rosa', 'Agulhas rosas que perseguem e explodem quando juntam.', 4, 'zarabatana', '#ff5af0', 'agulha', '#ff5af0', 'agulha', { dano: 1.2, cadencia: 0.07, pente: 30, teleguiado: 3, explosao: 8, municao: 300 }],
  ['mochila_protons', 'Mochila de Prótons', 'Raio contínuo que prende fantasmas. Não cruze os raios.', 4, 'laser', '#ff9a2e', 'laser', '#ffb43a', 'zap', { dano: 1.4, cadencia: 0.08, pente: 60, laser: true, alcance: 200, congela: 0.15, municao: 600 }],
  ['gordinho', 'O Gordinho', 'Lançador nuclear de bolso. Um tiro, uma sala a menos.', 4, 'lancador', '#cfd8dc', 'granada', '#ff9a2e', 'lancador', { dano: 25, cadencia: 2, pente: 1, recarga: 2.6, velocidade: 150, municao: 6, explosao: 70, tremor: 0.03 }],
  ['velha_pintada', 'Velha Pintada', 'Gatling gigante. Ninguém aguenta muito tempo na frente dela.', 4, 'gatling', '#e2452b', 'bala', '#ffe066', 'smg', { dano: 1.1, cadencia: 0.035, pente: 200, aquecimento: 1.4, municao: 800, perfura: 1 }],
  ['getsuga', 'Corte da Lua Negra', 'Ondas de energia em forma de lâmina que atravessam tudo.', 4, 'serra', '#1b1325', 'serra', '#e2452b', 'serra', { dano: 5, cadencia: 0.45, pente: 8, perfura: 99, tamanho: 1.8, velocidade: 260, municao: 80 }],
  // --- RARAS ---
  ['buster', 'Canhão de Braço Azul', 'Tiros de energia rápidos. Segura e solta, robô azul.', 3, 'pistola', '#4f9dff', 'bala_grande', '#7fd7ff', 'pistola', { dano: 2.4, cadencia: 0.14, pente: 3, recarga: 0.35, municao: -1, velocidade: 320 }],
  ['raio_zumbizador', 'Raio Zumbizador', 'Bolas verdes que explodem. Os zumbis odeiam.', 3, 'vagalume', '#7fdc8a', 'orbe', '#7fff4f', 'zap', { dano: 4, cadencia: 0.3, pente: 20, explosao: 18, velocidade: 240, municao: 160 }],
  ['arma_portais', 'Arma de Portais', 'Disparos que atravessam paredes. Agora você pensa com portais.', 3, 'laser', '#ff9a2e', 'bala_grande', '#4fa8ff', 'zap', { dano: 2.6, cadencia: 0.25, pente: 12, espectral: true, ricochete: 0, municao: 120 }],
  ['trilho', 'Canhão de Trilho', 'Um raio que atravessa tudo e todos. Recarrega devagar.', 3, 'laser', '#7fdc8a', 'laser', '#9cff6b', 'laser', { dano: 12, cadencia: 1.1, pente: 4, laser: true, alcance: 340, municao: 40 }],
  ['rasengan', 'Esfera Espiral', 'Uma esfera girando que puxa os monstros e explode.', 3, 'vazio', '#4f9dff', 'orbe', '#7fd7ff', 'vazio', { dano: 7, cadencia: 0.9, pente: 4, velocidade: 120, explosao: 28, atrator: true, municao: 32 }],
  ['leigan', 'Tiro Espiritual', 'Um tiro de dedo só, mas que atravessa a sala inteira.', 3, 'pistola', '#7fe8ff', 'bala_grande', '#bfefff', 'revolver', { dano: 14, cadencia: 1, pente: 1, recarga: 1, perfura: 99, velocidade: 380, tamanho: 1.8, municao: -1 }],
  ['positron', 'Rifle Pósitron', 'Raio laranja de longuíssimo alcance. Precisa de toda a energia do país.', 3, 'laser', '#ff9a2e', 'laser', '#ffb43a', 'laser', { dano: 9, cadencia: 0.9, pente: 5, laser: true, alcance: 400, municao: 40 }],
  ['pistola_ouro', 'Pistola de Ouro', 'Uma bala, um alvo. Mata quase tudo com um tiro.', 3, 'revolver', '#ffd23f', 'bala', '#ffd23f', 'revolver', { dano: 30, cadencia: 1, pente: 1, recarga: 1.2, municao: 12, velocidade: 420 }],
  ['arpao_escorpiao', 'Arpão do Escorpião', 'Vem cá! O arpão atravessa e puxa os monstros.', 3, 'zarabatana', '#ffd23f', 'agulha', '#ffd23f', 'agulha', { dano: 5, cadencia: 0.6, pente: 5, perfura: 3, atrator: true, municao: 50 }],
  ['ebano_marfim', 'Ébano e Marfim', 'Duas pistolas, o dobro de estilo. Munição infinita.', 3, 'pistola', '#f4ead6', 'bala', '#ffffff', 'pistola', { dano: 1.6, cadencia: 0.09, pente: 24, multiplos: 1, municao: -1 }],
  ['rifle_pulso', 'Rifle de Pulso', 'Rajada militar com um lança-granadas embaixo.', 3, 'metralhadora', '#3b3f4a', 'bala', '#ffb43a', 'smg', { dano: 1.4, cadencia: 0.07, pente: 40, fragmenta: 2, fragmentoExplode: true, municao: 240 }],
  ['granada_santa', 'Granada de Mão Santa', 'Conte até três. Nem dois, nem quatro. Três.', 3, 'lancador', '#ffd23f', 'granada', '#ffe066', 'lancador', { dano: 14, cadencia: 1.2, pente: 3, explosao: 46, municao: 18 }],
  // --- INCOMUNS ---
  ['pregadora', 'Pregadora', 'Pregos a toda velocidade. Ninguém fica de pé.', 2, 'metralhadora', '#7d8494', 'agulha', '#cfd8dc', 'agulha', { dano: 0.9, cadencia: 0.06, pente: 50, perfura: 1, municao: 300 }],
  ['flak', 'Canhão Flak', 'Uma bola de estilhaços que se parte ao bater.', 2, 'escopeta', '#ff9a2e', 'bala_grande', '#ffb43a', 'escopeta', { dano: 3, cadencia: 0.7, projeteis: 1, dispersao: 4, fragmenta: 8, pente: 6, municao: 48 }],
  ['luva_gravidade', 'Luva da Gravidade', 'Um campo que puxa os monstros para o mesmo ponto.', 2, 'tesla', '#ff9a2e', 'orbe', '#ffb43a', 'vazio', { dano: 2, cadencia: 0.8, pente: 4, atrator: true, velocidade: 140, municao: 40 }],
  ['lanca_tinta', 'Lança-Tinta', 'Jatos de tinta que deixam os monstros lentos.', 2, 'macarico', '#ff5af0', 'chama', '#ff5af0', 'macarico', { dano: 0.5, congela: 0.12, municao: 400 }],
  ['estrela_cuspida', 'Estrela Cuspida', 'Engole e cospe uma estrela que quica pela sala.', 2, 'pistola', '#ff8ac8', 'cristal', '#ffd23f', 'pistola', { dano: 3, cadencia: 0.5, pente: 6, ricochete: 4, municao: -1 }],
  ['blaster_contrabandista', 'Blaster do Contrabandista', 'Atira primeiro. Raio vermelho e forte.', 2, 'revolver', '#3b3f4a', 'bala_grande', '#e2452b', 'zap', { dano: 4.5, cadencia: 0.35, pente: 8, velocidade: 360, municao: -1 }],
  ['pistola_fase', 'Pistola de Fase', 'No modo atordoar: congela quem acerta.', 2, 'laser', '#cfd8dc', 'laser', '#7fd7ff', 'laser', { dano: 1.5, cadencia: 0.35, pente: 10, laser: true, congela: 0.5, municao: 100 }],
  ['chave_sonica', 'Chave de Fenda Sônica', 'Ondas sônicas que passam pelas paredes.', 2, 'tesla', '#7fdc8a', 'faisca', '#9cff6b', 'zap', { dano: 1.4, cadencia: 0.12, pente: 20, espectral: true, municao: 200 }],
  ['laser_patrulheiro', 'Laser do Patrulheiro Espacial', 'Ao infinito e além! Laser fininho e rápido.', 2, 'laser', '#7fdc8a', 'laser', '#e2452b', 'laser', { dano: 1.6, cadencia: 0.18, pente: 16, laser: true, municao: 160 }],
  ['espingarda_exterminador', 'Espingarda do Exterminador', 'Hasta la vista. Escopeta de alavanca muito forte.', 2, 'escopeta', '#3b3f4a', 'chumbo', '#ffb43a', 'escopeta', { dano: 1.6, projeteis: 8, empurrao: 220, municao: 40 }],
  ['tiara_lunar', 'Tiara Lunar', 'Pela lua! Uma tiara que vai e volta cortando.', 2, 'serra', '#ffd23f', 'serra', '#ffe066', 'serra', { dano: 3, bumerangue: true, perfura: 99, municao: -1, pente: 2 }],
  ['revolver_cowboy', 'Revólver do Caçador de Recompensas', 'Até mais, cowboy espacial. Seis tiros certeiros.', 2, 'revolver', '#3b3f4a', 'bala', '#ffe066', 'revolver', { dano: 4, cadencia: 0.18, pente: 6, recarga: 0.9, municao: -1 }],
  ['arco_heroi', 'Arco do Herói', 'Flechas que atravessam e vão longe.', 2, 'zarabatana', '#8a5a2b', 'agulha', '#f4ead6', 'agulha', { dano: 4, cadencia: 0.5, pente: 1, recarga: 0.3, perfura: 2, velocidade: 380, municao: -1 }],
  ['ora_ora', 'Rajada de Socos', 'ORA ORA ORA! Uma chuva de socos de energia.', 2, 'metralhadora', '#c86bff', 'bala_grande', '#c86bff', 'smg', { dano: 0.9, cadencia: 0.04, pente: 60, dispersao: 30, alcance: 90, empurrao: 80, municao: 600 }],
  ['luva_fogo', 'Luva do Alquimista de Fogo', 'Um estalar de dedos e tudo pega fogo.', 2, 'macarico', '#f4ead6', 'chama', '#ff4a2e', 'macarico', { dano: 0.8, explosao: 10, alcance: 120, municao: 300 }],
  ['lanca_trovao', 'Lança-Trovão', 'Lanças explosivas para gigantes. Dedique o seu coração.', 2, 'lancador', '#7d8494', 'foguete', '#ffd23f', 'foguete', { dano: 5, cadencia: 0.8, pente: 2, explosao: 22, municao: 24, teleguiado: 0.5 }],
  // --- COMUNS ---
  ['zapper', 'Zapper Laranja', 'Mira na tela e atira. O cachorro ri de você.', 1, 'pistola', '#ff9a2e', 'bala', '#ffffff', 'pistola', { dano: 3, cadencia: 0.4, pente: 6, velocidade: 400, municao: -1 }],
  ['estilingue', 'Estilingue', 'Pedrinhas que quicam nas paredes.', 1, 'pistola', '#8a5a2b', 'chumbo', '#a0784a', 'pistola', { dano: 1.6, cadencia: 0.3, ricochete: 2, municao: -1 }],
  ['pistola_agua', 'Pistola de Água', 'Pouco dano, muito empurrão. E deixa lento.', 1, 'pistola', '#4f9dff', 'bala_grande', '#7fd7ff', 'pistola', { dano: 0.6, cadencia: 0.08, pente: 40, empurrao: 200, congela: 0.08, municao: -1 }],
  ['lanca_argolas', 'Lança-Argolas', 'Argolas douradas que quicam e perseguem.', 1, 'ricochete', '#ffd23f', 'cristal', '#ffd23f', 'pistola', { dano: 1.4, ricochete: 3, teleguiado: 0.6, municao: -1 }],
  ['arremessa_bolas', 'Arremessa-Bolas de Monstrinho', 'Vai, bolinha! Quica e volta para a mão.', 1, 'pistola', '#e2452b', 'bala_grande', '#f4ead6', 'pistola', { dano: 2.4, cadencia: 0.45, pente: 6, bumerangue: true, municao: -1 }],
  ['tubaraozinho', 'Tubarãozinho', 'Uma metralhadorinha com cara de tubarão. Come munição.', 1, 'metralhadora', '#7d8494', 'bala', '#ffe066', 'smg', { dano: 0.6, cadencia: 0.05, pente: 50, municao: 400 }],
  ['lanca_confete', 'Lança-Confete', 'Festa! Confetes coloridos para todo lado.', 1, 'vela_romana', '#ff5af0', 'chumbo', '#ff5af0', 'escopeta', { dano: 0.8, projeteis: 6, dispersao: 50, explosao: 0, teleguiado: 0, municao: 90 }],
  ['bolas_neve', 'Canhão de Bolas de Neve', 'Bolas de neve grandes que congelam.', 1, 'lancador', '#bfefff', 'bala_grande', '#ffffff', 'gelo', { dano: 3, cadencia: 0.5, pente: 6, explosao: 0, congela: 0.3, velocidade: 220, municao: 60 }],
  ['rojao_junino', 'Rojão Junino', 'Olha o rojão! Explode em fogos coloridos.', 1, 'vela_romana', '#ffd23f', 'foguete', '#ffd23f', 'foguete', { dano: 2.4, projeteis: 1, cadencia: 0.6, explosao: 16, municao: 30 }],
  ['lanca_abelhas', 'Lança-Abelhas', 'Um enxame de abelhas que persegue e envenena.', 1, 'vagalume', '#ffd23f', 'vagalume', '#ffe066', 'vagalume', { dano: 0.7, projeteis: 4, veneno: true, teleguiado: 2, municao: 160 }],
  ['corneta', 'Corneta do Juízo', 'Uma onda de som que empurra todo mundo.', 1, 'escopeta', '#ffd23f', 'faisca', '#ffe066', 'zap', { dano: 0.7, projeteis: 7, dispersao: 70, empurrao: 260, alcance: 90, municao: 70 }],
  ['dardos_espuma', 'Lança-Dardos de Espuma', 'Dardos que quicam no chão... e nas paredes.', 1, 'zarabatana', '#ff9a2e', 'agulha', '#4f9dff', 'agulha', { dano: 1.2, cadencia: 0.2, pente: 12, ricochete: 1, municao: -1 }],
  ['choque_rato', 'Choque do Rato Amarelo', 'Choques que pulam entre os monstros.', 1, 'tesla', '#ffd23f', 'faisca', '#ffe066', 'zap', { dano: 1.4, cadencia: 0.35, eletrico: 2, municao: 140 }],
];
