// Itens ativos novos, itens de referência com efeitos especiais e itens exclusivos dos personagens.
// Os efeitos são as peças de src/sistemas/Efeitos.ts ("onde: mira" = onde o mouse aponta).
// Depois de mudar algo aqui: npm run gerar

// ---------- 100 itens ativos novos (tecla C) ----------
// [id, nome, descrição, ícone, cor, carga (salas), efeitos]
export const ATIVOS = [
  // --- Jujutsu Kaisen ---
  ['vazio_infinito', 'Domínio: Vazio Infinito', 'Informação infinita: todos os monstros travam por 5s e as balas somem.', 'livro', '#4fa8ff', 6, [['paralisar', { seg: 5 }], ['apagarBalas', {}], ['lento', { escala: 0.5, ms: 800 }]]],
  ['santuario', 'Domínio: Santuário Malevolente', 'Cortes invisíveis retalham a sala inteira por 4 segundos.', 'livro', '#e2452b', 6, [['cortes', { seg: 4, dano: 3 }]]],
  ['roxo_oco', 'Técnica Proibida: Roxo', 'Junta o azul e o vermelho: uma esfera roxa que apaga tudo no caminho.', 'orbe', '#b06bff', 5, [['projetilGigante', { dano: 40, tam: 4, cor: '#b06bff' }]]],
  ['lapso_azul', 'Lapso: Azul', 'Um ponto de atração onde você mira: suga os monstros.', 'orbe', '#4f9dff', 3, [['buracoNegro', { seg: 3, raio: 50, dano: 4 }]]],
  ['reversao_vermelho', 'Reversão: Vermelho', 'Repulsão: arremessa tudo para longe com uma explosão.', 'orbe', '#e2452b', 3, [['explosao', { onde: 'jogador', raio: 34, dano: 8 }], ['empurrar', { raio: 140, forca: 520, dano: 3 }]]],
  // --- One Piece ---
  ['haki_rei', 'Haki do Rei', 'Os fracos desmaiam: todos travam por 3s e levam dano.', 'coroa', '#c86bff', 5, [['paralisar', { seg: 3 }], ['danoTodos', { dano: 4 }]]],
  ['shambles', 'Room: Shambles', 'Troca de lugar com o monstro mais longe e corta a sala toda.', 'cubo', '#4fa8ff', 3, [['teleporte', { para: 'inimigo' }], ['danoTodos', { dano: 5 }]]],
  ['fruta_tremor', 'Fruta do Tremor', 'Racha o ar: terremoto que fere tudo e abre paredes.', 'esfera', '#f4ead6', 5, [['terremoto', { dano: 12 }]]],
  ['coup_de_burst', 'Coup de Burst', 'Um tiro de canhão de cola: dash gigante e intocável.', 'barril', '#ffd23f', 2, [['dashLongo', {}], ['invulneravel', { seg: 0.8 }]]],
  ['tambores_libertacao', 'Tambores da Libertação', 'Gear 5: dano x2, +40% velocidade, intocável e cura (10s).', 'chapeu_palha', '#ffffff', 8, [['buff', { stat: 'dano', mult: 2, seg: 10 }], ['buff', { stat: 'velocidade', mult: 1.4, seg: 10 }], ['invulneravel', { seg: 2 }], ['curar', { qtd: 20 }]]],
  // --- jogos ---
  ['granada_fragmentacao', 'Granada de Fragmentação', 'Explosão grande onde você mira.', 'bomba', '#7d8494', 2, [['explosao', { onde: 'mira', raio: 44, dano: 14 }]]],
  ['hadouken', 'Bola de Energia do Lutador', 'Uma bola de energia gigante para frente.', 'orbe', '#7fd7ff', 2, [['projetilGigante', { dano: 18, tam: 2.4, cor: '#7fd7ff', vel: 220 }]]],
  ['estrela_invencivel', 'Estrela da Invencibilidade', 'Intocável por 6s, mais rápido, e encostar machuca.', 'estrela', '#ffd23f', 6, [['invulneravel', { seg: 6 }], ['buff', { stat: 'velocidade', mult: 1.3, seg: 6 }], ['laminas', { n: 4, seg: 6, dano: 2, cor: '#ffd23f' }]]],
  ['pocao_hp', 'Poção Vermelha Grande', 'Cura 40 de chama.', 'frasco', '#e2452b', 4, [['curar', { qtd: 40 }]]],
  ['bomba_cruz', 'Bomba de Pavio Curto', 'Explode em volta e solta 4 chamas em cruz.', 'bomba', '#1b1325', 2, [['explosao', { onde: 'jogador', raio: 30, dano: 10 }], ['anel', { n: 4, dano: 6, vel: 160, tex: 'bala_grande', cor: '#ff9a2e', perfura: 99 }]]],
  ['ocarina_tempo', 'Ocarina do Tempo', 'Toca a música: câmera lenta longa e cura.', 'sopro', '#4fa8ff', 4, [['lento', { escala: 0.3, ms: 3000 }], ['curar', { qtd: 10 }]]],
  ['flecha_luz', 'Flechas de Luz', 'Um leque de 9 flechas de luz que atravessam.', 'pena', '#fff4b0', 2, [['leque', { n: 9, abertura: 50, dano: 4, perfura: 3, tex: 'agulha', cor: '#fff4b0', vel: 340 }]]],
  ['bau_mimico', 'Baú Mímico', 'Abre a boca: solta 15 gotas de cera... e morde.', 'cubo', '#8a5a2b', 3, [['cera', { n: 15, onde: 'jogador' }], ['sangria', { dano: 6, cura: 3 }]]],
  ['kit_medico', 'Kit Médico', 'Cura 20 e dá um escudo.', 'cubo', '#ffffff', 3, [['curar', { qtd: 20 }], ['escudo', {}]]],
  ['luva_antigravidade', 'Luva Antigravidade', 'Puxa tudo para onde você mira e solta numa explosão.', 'mao', '#ff9a2e', 3, [['buracoNegro', { seg: 2, raio: 50, dano: 10 }]]],
  ['ataque_aereo', 'Ataque Aéreo', 'Pede reforço: 8 bombas caem nos monstros.', 'pergaminho', '#e2452b', 5, [['meteoro', { n: 8, dano: 9, raio: 22 }]]],
  ['escudo_energia', 'Escudo de Energia', 'Recarrega o escudo e fica intocável por 1,5s.', 'escudo', '#7fd7ff', 2, [['escudo', {}], ['invulneravel', { seg: 1.5 }]]],
  ['moeda_dobrada', 'Moeda Dobrada', 'Cara: cera. Coroa: críticos. Dá os dois.', 'moeda', '#ffd23f', 2, [['cera', { n: 6, onde: 'jogador' }], ['criticos', { n: 6 }]]],
  ['totem_imortal', 'Totem da Imortalidade', 'Intocável por 2s e cura 15.', 'runa', '#ffd23f', 4, [['invulneravel', { seg: 2 }], ['curar', { qtd: 15 }]]],
  ['bola_neve', 'Bola de Neve Gigante', 'Leque de bolas de neve que congelam.', 'floco', '#ffffff', 2, [['leque', { n: 7, abertura: 40, dano: 3, congela: 0.6, cor: '#ffffff' }]]],
  ['cartucho_bonus', 'Cartucho Bônus', 'Munição cheia e 5 tiros de graça.', 'pente', '#7d8494', 3, [['municao', {}], ['eco', {}], ['eco', {}], ['eco', {}], ['eco', {}], ['eco', {}]]],
  ['pokebola', 'Bola de Captura', 'Joga a bola: um bichinho caça os monstros por 15s.', 'esfera', '#e2452b', 4, [['caes', { n: 1, seg: 15, cor: '#ffd23f' }]]],
  // --- animes ---
  ['jutsu_clones', 'Jutsu dos Clones das Sombras', 'Dois clones atiram junto com você por 10s.', 'bandana', '#4f9dff', 4, [['clone', { seg: 10 }]]],
  ['esfera_coletiva', 'Esfera de Energia Coletiva', 'Levanta as mãos: uma esfera gigante e lenta.', 'esfera', '#7fd7ff', 7, [['projetilGigante', { dano: 60, tam: 5, cor: '#7fd7ff', vel: 110 }]]],
  ['corte_lunar', 'Corte Lunar', 'Um leque de lâminas de energia negra.', 'mascara', '#1b1325', 3, [['leque', { n: 5, abertura: 30, dano: 8, perfura: 99, tex: 'serra', cor: '#e2452b', vel: 280 }]]],
  ['respiracao_trovao', 'Respiração do Trovão', 'Um dash relâmpago e raios em todos.', 'raio', '#ffe066', 3, [['dashLongo', {}], ['raioCeu', { n: 6, dano: 5 }]]],
  ['respiracao_agua', 'Respiração da Água', 'Ondas que cortam e empurram em volta.', 'lagrima', '#4f9dff', 3, [['anel', { n: 20, dano: 2.5, tex: 'serra', cor: '#7fd7ff', perfura: 2 }], ['empurrar', { raio: 70, forca: 260 }]]],
  ['olho_copiador_a', 'Olho que Copia', 'Copia o golpe: as balas inimigas viram suas.', 'olho', '#e2452b', 3, [['apagarBalas', { converter: true }]]],
  ['pagina_arrancada', 'Página Arrancada', 'Escreve um nome: mata quem tem menos de 40% da vida.', 'livro', '#2a2033', 4, [['matarFracos', { fracao: 0.4 }]]],
  ['rajada_socos', 'Stand: Rajada de Socos', 'ORA ORA! Cadência x3 por 3s e 3 tiros de graça.', 'mao', '#c86bff', 4, [['buff', { stat: 'cadencia', mult: 3, seg: 3 }], ['eco', {}], ['eco', {}], ['eco', {}]]],
  ['mundo_parado', 'O Mundo Parado', 'Para o tempo: tudo trava 4s e as balas somem.', 'relogio_p', '#ffd23f', 6, [['paralisar', { seg: 4 }], ['apagarBalas', {}], ['lento', { escala: 0.25, ms: 1200 }]]],
  ['manto_raposa', 'Manto da Raposa', 'Chama laranja: dano x1,6 e lâminas de fogo por 8s.', 'chama', '#ff9a2e', 5, [['buff', { stat: 'dano', mult: 1.6, seg: 8 }], ['queimar', { seg: 4 }], ['laminas', { n: 3, seg: 8, dano: 2, cor: '#ff9a2e' }]]],
  ['roda_adaptacao', 'Roda da Adaptação', 'Gira: escudo, cura e um golpe em tudo.', 'runa', '#cfd8dc', 5, [['escudo', {}], ['curar', { qtd: 12 }], ['danoTodos', { dano: 6 }]]],
  ['grito_tita', 'Grito do Titã', 'Um rugido que trava e empurra tudo.', 'dente', '#a0784a', 4, [['paralisar', { seg: 2 }], ['empurrar', { raio: 160, forca: 400, dano: 2 }]]],
  ['kunai_explosiva', 'Kunai Explosiva', 'Teleporta para onde mira e explode.', 'pena', '#ff4a2e', 2, [['teleporte', {}], ['explosao', { onde: 'jogador', raio: 32, dano: 9 }]]],
  // --- filmes e séries ---
  ['sabre_luz', 'Sabre de Luz', 'Lâminas de luz giram em você por 6s.', 'cristal', '#4fa8ff', 3, [['laminas', { n: 3, seg: 6, dano: 3, cor: '#7fd7ff' }]]],
  ['empurrao_forca', 'Empurrão da Força', 'Use a Força: empurra tudo e apaga as balas.', 'mao', '#7fd7ff', 2, [['empurrar', { raio: 200, forca: 450, dano: 2 }], ['apagarBalas', {}]]],
  ['pocao_polissuco', 'Poção Polissuco', 'Vira outra pessoa: um monstro troca de lugar com você.', 'frasco', '#8a7a4a', 2, [['teleporte', { para: 'inimigo' }], ['invulneravel', { seg: 1 }]]],
  ['volta_tempo', 'Volta no Tempo', 'Cura 30 e o tempo desacelera.', 'ampulheta', '#ffd23f', 5, [['curar', { qtd: 30 }], ['lento', { escala: 0.5, ms: 800 }]]],
  ['martelo_trovao', 'Martelo do Trovão', 'Só os dignos: 10 raios caem do céu.', 'raio', '#cfd8dc', 5, [['raioCeu', { n: 10, dano: 7 }]]],
  ['manopla', 'Manopla das Joias', 'Estala os dedos: metade da sala vira pó.', 'mao', '#ffd23f', 8, [['matarFracos', { fracao: 0.55 }], ['danoTodos', { dano: 10 }]]],
  ['neuralizador', 'Neuralizador', 'Flash! Todos ficam atordoados por 3s.', 'lente', '#ffffff', 3, [['paralisar', { seg: 3 }]]],
  ['armadilha_fantasmas', 'Armadilha de Fantasmas', 'Suga tudo para onde você mira e prende.', 'cubo', '#ffe066', 3, [['buracoNegro', { seg: 3, raio: 60, dano: 5, onde: 'mira' }], ['paralisar', { seg: 1 }]]],
  ['capacitor_fluxo', 'Capacitor de Fluxo', '88 milhas por hora: dash longo e câmera lenta.', 'raio', '#7fd7ff', 2, [['dashLongo', {}], ['lento', { escala: 0.4, ms: 1000 }]]],
  ['tempo_bala', 'Tempo de Bala', 'Câmera lenta longa e as balas inimigas viram suas.', 'pilula', '#7fdc8a', 5, [['lento', { escala: 0.25, ms: 2500 }], ['apagarBalas', { converter: true }]]],
  ['chave_sonica_a', 'Chave Sônica', 'Abre portas: um tremor que racha as paredes.', 'chave', '#7fdc8a', 1, [['terremoto', { dano: 2 }]]],
  ['cabine_tempo', 'Cabine no Tempo', 'Some e aparece num lugar seguro, curado.', 'cubo', '#2a4fd0', 3, [['teleporte', { para: 'aleatorio' }], ['curar', { qtd: 12 }]]],
  ['flor_invertida', 'Flor do Mundo Invertido', 'Pétalas: um anel de 24 balas que atravessam.', 'trevo', '#e2452b', 3, [['anel', { n: 24, dano: 2.5, perfura: 2, cor: '#e2452b' }]]],
  ['walkie_talkie', 'Walkie-Talkie', 'Chama os amigos: 2 cães e uma torre de luz.', 'sino', '#ffd23f', 5, [['caes', { n: 2, seg: 12 }], ['torre', {}]]],
  ['sapatos_rubi', 'Sapatos de Rubi', 'Bata os calcanhares: some, cura e ganha escudo.', 'sapato', '#e2452b', 3, [['teleporte', { para: 'aleatorio' }], ['curar', { qtd: 15 }], ['escudo', {}]]],
  ['flauta_magica', 'Flauta Mágica', 'Os monstros dançam: travam 2s e levam dano.', 'sopro', '#ffd23f', 3, [['paralisar', { seg: 2 }], ['danoTodos', { dano: 3 }]]],
  ['lampada_genio_a', 'Lâmpada do Gênio', 'Três desejos: cura, cera e críticos.', 'lamparina', '#ffd23f', 6, [['curar', { qtd: 20 }], ['cera', { n: 10, onde: 'jogador' }], ['criticos', { n: 10 }]]],
  ['tesoura_destino', 'Tesoura do Destino', 'Corta os fios: mata quem tem menos de 30% e cura.', 'mao', '#cfd8dc', 3, [['matarFracos', { fracao: 0.3 }], ['curar', { qtd: 8 }]]],
  ['raio_encolhedor_a', 'Controle Remoto Universal', 'Pausa: tudo para por 2s.', 'cubo', '#3b3f4a', 3, [['paralisar', { seg: 2 }], ['lento', { escala: 0.3, ms: 800 }]]],
  // --- originais ---
  ['vulcao', 'Vulcão de Bolso', 'Erupção: 6 meteoros e fogo em todos.', 'pedra', '#e2452b', 5, [['meteoro', { n: 6, dano: 10 }], ['queimar', { seg: 4 }]]],
  ['arco_iris', 'Arco-Íris', 'Sete cores: um leque largo de 21 balas.', 'estrela', '#ff5af0', 3, [['leque', { n: 21, abertura: 120, dano: 2.5, cor: '#ff5af0' }]]],
  ['ninho_vespas', 'Ninho de Vespas', '14 vespas que perseguem e envenenam.', 'frasco', '#ffd23f', 3, [['teleguiadas', { n: 14, dano: 1.5, cor: '#ffd23f' }], ['envenenar', { seg: 3 }]]],
  ['inverno_eterno', 'Inverno Eterno', 'Congela a sala 4s e espalha gelo no chão.', 'floco', '#bfefff', 4, [['congelar', { seg: 4 }], ['nuvem', { onde: 'jogador', raio: 50, seg: 6, dps: 1, tipo: 'gelo' }]]],
  ['chuva_acida', 'Chuva Ácida', 'Envenena a sala e solta uma nuvem onde mira.', 'lagrima', '#9cff6b', 3, [['envenenar', { seg: 6 }], ['nuvem', { onde: 'mira', raio: 40, seg: 6, dps: 3, tipo: 'veneno' }]]],
  ['tempestade_laminas', 'Tempestade de Lâminas', '8 lâminas giram em você por 5s.', 'osso', '#cfd8dc', 4, [['laminas', { n: 8, seg: 5, dano: 1.8 }]]],
  ['velas_bolo', 'Velas de Aniversário', 'Faça um pedido: um anel de 16 fogos de artifício.', 'bolo', '#ff8ac8', 3, [['anel', { n: 16, dano: 3, tex: 'foguete', cor: '#ff5af0', vel: 200 }]]],
  ['farol', 'Farol', 'Um feixe gira em volta de você por 4s.', 'lamparina', '#fff4b0', 4, [['laserGiro', { seg: 4, dano: 7 }]]],
  ['ventilador', 'Ventilador de Teto', 'Empurra tudo e acelera você.', 'pena', '#c8f0e0', 1, [['empurrar', { raio: 120, forca: 300 }], ['buff', { stat: 'velocidade', mult: 1.4, seg: 4 }]]],
  ['ima_gigante', 'Ímã Gigante', 'Atrai fortuna: solta 6 gotas de cera em você.', 'ima', '#e2452b', 2, [['cera', { n: 6, onde: 'jogador' }]]],
  ['bola_cristal', 'Bola de Cristal', 'Vê o futuro: revela o mapa e dá 5 críticos.', 'esfera', '#c8a0ff', 3, [['revelarMapa', {}], ['criticos', { n: 5 }]]],
  ['ampulheta_areia', 'Ampulheta de Areia', 'Câmera lenta e pernas mais rápidas.', 'ampulheta', '#e8d8b0', 2, [['lento', { escala: 0.3, ms: 1500 }], ['buff', { stat: 'velocidade', mult: 1.2, seg: 3 }]]],
  ['banana_dinamite', 'Banana de Dinamite', 'Joga onde mira: explosão enorme.', 'dinamite', '#e2452b', 3, [['explosao', { onde: 'mira', raio: 60, dano: 20 }]]],
  ['caixa_minas', 'Caixa de Minas', 'Planta 10 minas em volta.', 'barril', '#7d8494', 3, [['minas', { n: 10, dano: 10 }]]],
  ['incenso', 'Incenso Sagrado', 'Fumaça que queima os monstros em volta e cura 10.', 'votiva', '#c8a0ff', 3, [['nuvem', { onde: 'jogador', raio: 60, seg: 6, dps: 3, tipo: 'fogo' }], ['curar', { qtd: 10 }]]],
  ['olho_tempestade', 'Olho da Tempestade', 'Raios em cadeia saem de você 3 vezes.', 'olho', '#ffe066', 3, [['raios', { saltos: 6, dano: 4 }], ['raios', { saltos: 6, dano: 4 }], ['raios', { saltos: 6, dano: 4 }]]],
  ['espelho_duplo', 'Espelho Duplo', 'Duas cópias suas por 6s e um escudo.', 'espelho', '#e8f0ff', 4, [['clone', { seg: 6 }], ['escudo', {}]]],
  ['sangue_frio', 'Sangue Frio', 'Gela a sala e suga a vida de 4 monstros.', 'gota_sangue', '#8fe3ff', 4, [['congelar', { seg: 2 }], ['sangria', { dano: 5, cura: 3 }], ['sangria', { dano: 5, cura: 3 }], ['sangria', { dano: 5, cura: 3 }], ['sangria', { dano: 5, cura: 3 }]]],
  ['show_fogos', 'Show de Fogos', '5 meteoros coloridos e um leque de foguetes.', 'estrela', '#ffd23f', 4, [['meteoro', { n: 5, dano: 7 }], ['leque', { n: 7, abertura: 70, dano: 3, tex: 'foguete', cor: '#ff5af0' }]]],
  ['cartola', 'Cartola do Mágico', 'Tira da cartola: 3 cães, cera e um escudo.', 'chapeu', '#1b1325', 5, [['caes', { n: 3, seg: 10, cor: '#ffffff' }], ['cera', { n: 5, onde: 'jogador' }], ['escudo', {}]]],
  ['relampago_globular', 'Relâmpago Globular', 'Uma esfera elétrica onde mira e raios em cadeia.', 'raio', '#ffe066', 3, [['buracoNegro', { seg: 3, raio: 30, dano: 4, onde: 'mira' }], ['raios', { saltos: 5, dano: 3 }]]],
  ['quebra_cabeca', 'Quebra-Cabeça Antigo', 'Rola os itens da sala e troca sua arma.', 'cubo', '#ffd23f', 4, [['rolarItens', {}], ['trocarArma', {}]]],
  ['furia_berserker', 'Fúria Berserker', 'Perde 15 de chama: dano x2 e cadência x1,5 por 8s.', 'mascara', '#e2452b', 2, [['custo', { chama: 15 }], ['buff', { stat: 'dano', mult: 2, seg: 8 }], ['buff', { stat: 'cadencia', mult: 1.5, seg: 8 }]]],
  ['oracao', 'Oração da Velinha', 'Cura 15 e protege por 2s.', 'votiva', '#fff4b0', 3, [['curar', { qtd: 15 }], ['invulneravel', { seg: 2 }]]],
  ['tufao', 'Tufão', 'Um ciclone puxa os monstros para você e corta.', 'sopro', '#c8f0e0', 3, [['buracoNegro', { seg: 2.5, raio: 70, dano: 3, onde: 'jogador' }], ['laminas', { n: 3, seg: 3, dano: 2 }]]],
  ['sementes_explosivas', 'Sementes Explosivas', 'Planta 5 minas e envenena a sala.', 'trevo', '#7fdc8a', 3, [['minas', { n: 5, dano: 8 }], ['envenenar', { seg: 3 }]]],
  ['eclipse', 'Eclipse', 'Escuridão: intocável 2s, todos levam dano e você ganha críticos.', 'esfera', '#1b1325', 4, [['invulneravel', { seg: 2 }], ['danoTodos', { dano: 7 }], ['criticos', { n: 5 }]]],
  ['metralha_cera', 'Metralha de Cera', 'Um leque de 30 gotas de cera quente.', 'gota_sangue', '#ffb43a', 3, [['leque', { n: 30, abertura: 90, dano: 1.5, queima: true, cor: '#ffb43a' }]]],
  ['raizes_vivas', 'Raízes Vivas', 'Raízes prendem e envenenam todos por 3s.', 'trevo', '#4a8a3a', 3, [['paralisar', { seg: 3 }], ['envenenar', { seg: 3 }]]],
  ['cometa', 'Cometa', 'Uma pedra em chamas que atravessa a sala.', 'pedra', '#ff9a2e', 3, [['projetilGigante', { dano: 25, tam: 3, cor: '#ff9a2e', vel: 260 }], ['queimar', { seg: 2 }]]],
  ['bumerangue_prata', 'Bumerangue de Prata', 'Cinco lâminas em leque que atravessam tudo.', 'bumerangue', '#cfd8dc', 2, [['leque', { n: 5, abertura: 50, dano: 4, perfura: 99, tex: 'serra', cor: '#cfd8dc', vel: 220 }]]],
  ['harpa_celestial', 'Harpa Celestial', 'Notas que curam 8 e soltam um raio.', 'sino', '#fff4b0', 2, [['curar', { qtd: 8 }], ['raios', { saltos: 3, dano: 3 }]]],
  ['vela_derretida', 'Vela Derretida', 'Gasta 10 de chama: o chão em volta vira lava.', 'vela_grossa', '#ff7a2e', 1, [['custo', { chama: 10 }], ['nuvem', { onde: 'jogador', raio: 70, seg: 6, dps: 4, tipo: 'fogo' }]]],
  ['pergaminho_fogo', 'Pergaminho de Fogo', 'Um leque de 12 bolas de fogo.', 'pergaminho', '#ff4a2e', 2, [['leque', { n: 12, abertura: 70, dano: 3, queima: true, cor: '#ff4a2e' }]]],
  ['pergaminho_gelo', 'Pergaminho de Gelo', 'Um leque de 12 estilhaços de gelo.', 'pergaminho', '#8fe3ff', 2, [['leque', { n: 12, abertura: 70, dano: 2.5, congela: 0.5, tex: 'cristal', cor: '#8fe3ff' }]]],
  ['pergaminho_trovao', 'Pergaminho do Trovão', 'Raios caem em 8 monstros.', 'pergaminho', '#ffe066', 3, [['raioCeu', { n: 8, dano: 6 }]]],
  ['moeda_barqueiro', 'Moeda do Barqueiro', 'Paga a travessia: perde 10 de chama e mata os fracos.', 'moeda', '#7d8494', 3, [['custo', { chama: 10 }], ['matarFracos', { fracao: 0.5 }]]],
  ['orbe_sombras', 'Orbe das Sombras', 'Clones, críticos e intocável: o kit do assassino.', 'orbe', '#b06bff', 5, [['clone', { seg: 5 }], ['criticos', { n: 8 }], ['invulneravel', { seg: 1 }]]],
  ['pedra_runas', 'Pedra das Runas', 'Escudo, lâminas e câmera lenta.', 'runa', '#c8a0ff', 4, [['escudo', {}], ['laminas', { n: 4, seg: 5, dano: 2 }], ['lento', { escala: 0.5, ms: 800 }]]],
  ['apito_dragao', 'Apito do Dragão', 'Um dragão passa: fogo em tudo e 4 meteoros.', 'sopro', '#e2452b', 6, [['queimar', { seg: 6 }], ['meteoro', { n: 4, dano: 12, raio: 30 }]]],
  ['ultima_chama', 'A Última Chama', 'Enche a chama, +5 de chama máxima e intocável 2s.', 'chama', '#fff4b0', 8, [['curar', { qtd: 999 }], ['chamaMax', { qtd: 5 }], ['invulneravel', { seg: 2 }]]],
];

// ---------- itens de Jujutsu Kaisen, One Piece e outros com efeitos especiais ----------
// [id, nome, descrição, ícone, cor, raridade, efeito, etiquetas]
export const REFERENCIAS_ESPECIAIS = [
  // Jujutsu Kaisen
  ['dedo_rei', 'Dedo do Rei das Maldições', '+25% dano. Ao matar (20%): cortes retalham a sala. Monstros +15% vida.', 'osso', '#c0303a', 3, { stats: { dano: 1.25, vidaInimigos: 1.15 }, maldito: true, gatilhos: [{ quando: 'matar', chance: 0.2, cd: 4, efeitos: [['cortes', { seg: 0.8, dano: 2 }]] }] }, ['sangue', 'osso']],
  ['punho_divergente', 'Punho Divergente', 'Cada acerto bate de novo um instante depois (50% do dano).', 'mao', '#4f9dff', 3, { passivos: ['golpeDuplo'] }, ['eco', 'luva']],
  ['faisca_negra', 'Faísca Negra', 'Às vezes o golpe sai 2,5x mais forte, com um raio negro.', 'raio', '#e2452b', 3, { passivos: ['raioNegro'] }, ['raio', 'sombra']],
  ['seis_olhos', 'Seis Olhos', 'Infinito: balas inimigas perto de você ficam quase paradas. +10% crítico.', 'olho', '#4fa8ff', 3, { passivos: ['infinito'], stats: { critico: 0.1 } }, ['olho', 'tempo']],
  ['tecnica_reversa', 'Técnica Reversa', 'No parry: cura 6. +10 chama máx.', 'coracao', '#7fd7ff', 2, { stats: { chamaMax: 10 }, gatilhos: [{ quando: 'parry', efeitos: [['curar', { qtd: 6 }]] }] }, ['coracao', 'luz']],
  ['caes_divinos', 'Cães Divinos', 'Dois cães (um preto, um branco) caçam os monstros para sempre.', 'dente', '#1b1325', 3, { passivos: ['caes'] }, ['sombra', 'dente']],
  ['boneco_palha', 'Boneco de Palha', 'Ressonância: acertar um monstro machuca outro (30%).', 'vela', '#c99a62', 2, { passivos: ['ressonancia'] }, ['raio', 'mascara']],
  ['energia_maldita', 'Energia Amaldiçoada', 'A cada 6 tiros: 3 balas roxas que perseguem.', 'chama', '#b06bff', 2, { gatilhos: [{ quando: 'tiro', cada: 6, efeitos: [['teleguiadas', { n: 3, dano: 2, cor: '#b06bff' }]] }] }, ['olhar', 'sombra']],
  // One Piece
  ['fruta_borracha', 'Fruta da Borracha', 'Gomu Gomu: balas vão e voltam e empurram muito. Dash volta 40% antes.', 'esfera', '#c86bff', 3, { mods: { bumerangue: true }, stats: { empurrao: 1.8, cooldownDash: 0.6 } }, ['mola', 'vento']],
  ['fruta_fogo', 'Fruta do Fogo', 'Balas incendeiam e o dash deixa fogo. Chama vermelha.', 'esfera', '#ff4a2e', 3, { mods: { queima: true }, passivos: ['mera'], visual: { chama: 'vermelha' } }, ['fogo', 'vento']],
  ['fruta_gelo', 'Fruta do Gelo', '25% de congelar, e o dash deixa um rastro de gelo.', 'esfera', '#8fe3ff', 3, { mods: { congela: 0.25 }, gatilhos: [{ quando: 'dash', cd: 0.6, efeitos: [['nuvem', { raio: 22, seg: 3, dps: 1, tipo: 'gelo' }]] }], visual: { chama: 'ciano' } }, ['gelo', 'vento']],
  ['haki_armamento', 'Haki do Armamento', '+20% dano e atravessa escudos.', 'mao', '#1b1325', 3, { stats: { dano: 1.2 }, passivos: ['haki'] }, ['terra', 'lamina']],
  ['tres_espadas', 'Estilo de Três Espadas', 'Cada tiro também solta dois cortes de espada.', 'osso', '#7fdc8a', 3, { passivos: ['santoryu'] }, ['lamina', 'eco']],
  ['perna_diabo', 'Perna do Diabo', 'O dash chuta e queima os monstros. +10% velocidade.', 'sapato', '#ff7a2e', 2, { passivos: ['diableJambe'], stats: { velocidade: 1.1 } }, ['fogo', 'bota']],
  ['mapa_grande_rota', 'Mapa da Grande Rota', 'Ao entrar numa sala: revela o mapa. +30% cera.', 'pergaminho', '#ffd23f', 2, { stats: { ceraBonus: 1.3 }, gatilhos: [{ quando: 'sala', efeitos: [['revelarMapa', {}]] }] }, ['ouro', 'pergaminho']],
  // outros
  ['anel_senhor_fogo', 'Anel do Senhor do Fogo', 'Aura: quem chega perto queima.', 'anel', '#ff7a2e', 3, { passivos: ['aura'] }, ['fogo', 'anel']],
];

// ---------- melhorias: efeitos especiais para os itens de referência que já existiam ----------
export const MELHORIAS = {
  estrela_piscante: { passivos: ['diableJambe'], extra: 'O dash machuca quem estiver no caminho.' },
  triangulo_dourado: { gatilhos: [{ quando: 'combo', efeitos: [['laserGiro', { seg: 1.5, dano: 6 }]] }], extra: 'A cada 10 de combo, um feixe dourado gira.' },
  fogueira: { gatilhos: [{ quando: 'limpar', efeitos: [['curar', { qtd: 6 }]] }], extra: 'Ao limpar a sala, cura 6.' },
  pastilha_poder: { gatilhos: [{ quando: 'matar', chance: 0.25, efeitos: [['buff', { stat: 'velocidade', mult: 1.3, seg: 2 }]] }], extra: 'Ao matar: corre mais por 2s.' },
  d20: { gatilhos: [{ quando: 'critico', chance: 0.2, cd: 1, efeitos: [['explosao', { raio: 24, dano: 6 }]] }], extra: 'No crítico (20%): explosão.' },
  esfera_estrelas: { gatilhos: [{ quando: 'limpar', chance: 0.2, efeitos: [['cera', { n: 8, onde: 'jogador' }]] }], extra: 'Ao limpar (20%): 8 gotas de cera.' },
  caderno_morte: { gatilhos: [{ quando: 'tiro', cada: 30, efeitos: [['matarFracos', { fracao: 0.2 }]] }], extra: 'A cada 30 tiros, mata os fracos.' },
  olho_copiador: { gatilhos: [{ quando: 'parry', efeitos: [['eco', {}], ['eco', {}]] }], extra: 'No parry: copia dois tiros.' },
  vira_tempo: { gatilhos: [{ quando: 'dano', efeitos: [['lento', { escala: 0.3, ms: 1200 }]] }], extra: 'Ao levar dano: o tempo desacelera.' },
  pilula_vermelha: { gatilhos: [{ quando: 'dash', cd: 1.5, efeitos: [['lento', { escala: 0.5, ms: 400 }]] }], extra: 'Ao dar dash: tempo de bala.' },
  pato_borracha: { gatilhos: [{ quando: 'dano', chance: 0.5, efeitos: [['criticos', { n: 5 }]] }], extra: 'Ao levar dano (50%): 5 críticos.' },
  caixa_pandora: { gatilhos: [{ quando: 'sala', efeitos: [['meteoro', { n: 2, dano: 8 }]] }], extra: 'Ao entrar: 2 meteoros caem.' },
  reator_peito: { gatilhos: [{ quando: 'tempo', cada: 5, efeitos: [['raios', { saltos: 3, dano: 3 }]] }], extra: 'A cada 5s: raio em cadeia.' },
  anel_juramento: { gatilhos: [{ quando: 'tiro', cada: 20, efeitos: [['laminas', { n: 2, seg: 3, dano: 1.5, cor: '#7fdc8a' }]] }], extra: 'A cada 20 tiros: construções verdes giram em você.' },
  ovo_dragao: { gatilhos: [{ quando: 'matar', chance: 0.2, efeitos: [['nuvem', { raio: 22, seg: 3, dps: 3, tipo: 'fogo' }]] }], extra: 'Ao matar (20%): fogo no chão.' },
  medalhao_bruxo: { gatilhos: [{ quando: 'sala', efeitos: [['criticos', { n: 3 }]] }], extra: 'Ao entrar: 3 críticos.' },
  cabine_azul: { gatilhos: [{ quando: 'dano', chance: 0.25, efeitos: [['teleporte', { para: 'aleatorio' }]] }], extra: 'Ao levar dano (25%): some e aparece longe.' },
  cogumelo_vermelho: { gatilhos: [{ quando: 'dano', efeitos: [['empurrar', { raio: 50, forca: 300 }]] }], extra: 'Ao levar dano: empurra tudo.' },
  bandana_ninja: { gatilhos: [{ quando: 'dash', cd: 3, efeitos: [['clone', { seg: 2 }]] }], extra: 'Ao dar dash: clones por 2s.' },
};

// ---------- itens exclusivos dos personagens (só aparecem para eles; começam com eles) ----------
export const EXCLUSIVOS = [
  ['tatuagem_e', 'Tatuagem "E"', 'A tatuagem do Luiz: +12% dano, +8% crítico. No crítico (25%): raio em cadeia.', 'runa', '#1b1325', 3,
    { stats: { dano: 1.12, critico: 0.08 }, gatilhos: [{ quando: 'critico', chance: 0.25, cd: 0.5, efeitos: [['raios', { saltos: 3, dano: 3 }]] }], exclusivo: 'luiz' }, ['sorte', 'runa']],
  ['sorriso_luiz', 'Sorriso do Luiz', 'A foto do Luiz no bolso: com pouca chama, ele aparece, cura 8 e protege (a cada 4s). +10 chama máx.', 'coracao', '#ff8ac8', 3,
    { stats: { chamaMax: 10 }, gatilhos: [{ quando: 'chamaBaixa', cada: 4, efeitos: [['curar', { qtd: 8 }], ['escudo', {}]] }], exclusivo: 'ana' }, ['coracao', 'luz']],
  ['capuz_pelucia', 'Capuz de Pelúcia', 'Quentinho: a chama queima 20% mais devagar e -10% de dano recebido.', 'capa', '#c99a62', 2,
    { stats: { decaimento: 0.8, danoRecebido: 0.9 }, exclusivo: 'ana' }, ['capa', 'terra']],
  ['bigode_lendario', 'Bigode Lendário', 'Monstros que encostam levam 6 e voam longe. +25 chama máx.', 'mascara', '#3a2a20', 3,
    { stats: { espinhos: 6, chamaMax: 25, empurrao: 1.3 }, exclusivo: 'henrique' }, ['terra', 'coracao']],
];

// ---------- relíquias dos personagens: vencer um final com o personagem libera a dele ----------
export const RELIQUIAS = [
  ['rel_vela', 'Pavio Original', 'O pavio da primeira vela: +10 chama máx. Ao limpar a sala, cura 4.', 'pavio', '#ffe066', 2,
    { stats: { chamaMax: 10 }, gatilhos: [{ quando: 'limpar', efeitos: [['curar', { qtd: 4 }]] }] }, ['luz', 'vela']],
  ['rel_luiz', 'Caneta do Criador', 'Quem fez o jogo desenha o que precisa: ao matar (6%), aparece um baú.', 'pergaminho', '#f4ead6', 3,
    { gatilhos: [{ quando: 'matar', chance: 0.06, cd: 15, efeitos: [['bau', {}]] }] }, ['sorte', 'pergaminho']],
  ['rel_ana', 'Foto Revelada', 'Ao entrar numa sala: um flash trava todos por 1,2s e seus 2 próximos tiros são críticos.', 'lente', '#ff8ac8', 3,
    { gatilhos: [{ quando: 'sala', efeitos: [['paralisar', { seg: 1.2 }], ['criticos', { n: 2 }]] }] }, ['luz', 'olho']],
  ['rel_henrique', 'Abraço de Urso', '+15 chama máx. Ao levar dano: empurra tudo em volta e cura 5.', 'coracao', '#a0784a', 3,
    { stats: { chamaMax: 15 }, gatilhos: [{ quando: 'dano', efeitos: [['empurrar', { raio: 70, forca: 360, dano: 2 }], ['curar', { qtd: 5 }]] }] }, ['terra', 'coracao']],
  ['rel_fosforo', 'Palito de Reserva', 'Uma vez por partida: quando a chama acabar, você reacende com metade dela.', 'pavio_curto', '#e2452b', 3,
    { passivos: ['renascer'] }, ['fogo', 'vela']],
  ['rel_lamparina', 'Óleo Eterno', 'A chama queima 30% mais devagar e ilumina 20% mais.', 'lamparina', '#7fd7ff', 2,
    { stats: { decaimento: 0.7, luz: 1.2 } }, ['luz', 'frasco']],
  ['rel_aniversario', 'Bolo Surpresa', 'Ao limpar a sala (10%): um item aparece num pedestal.', 'bolo', '#ff8ac8', 3,
    { gatilhos: [{ quando: 'limpar', chance: 0.1, efeitos: [['itemSurpresa', {}]] }] }, ['sorte', 'ouro']],
  ['rel_isqueiro', 'Pedra de Isqueiro', 'Ao dar dash: um anel de 8 faíscas de fogo.', 'brasa', '#ff9a2e', 2,
    { gatilhos: [{ quando: 'dash', cd: 0.8, efeitos: [['anel', { n: 8, dano: 1.5, cor: '#ff9a2e' }], ['queimar', { raio: 40, seg: 2 }]] }] }, ['fogo', 'bota']],
  ['rel_bruxinha', 'Caldeirão Borbulhante', 'A cada 6s em combate: uma nuvem de veneno cai num monstro.', 'frasco', '#9cff6b', 2,
    { gatilhos: [{ quando: 'tempo', cada: 6, efeitos: [['nuvem', { onde: 'inimigo', raio: 30, seg: 5, dps: 3, tipo: 'veneno' }]] }] }, ['veneno', 'frasco']],
  ['rel_cavaleiro', 'Brasão da Ordem', 'Um escudo por sala e -10% de dano recebido.', 'escudo', '#cfd8dc', 3,
    { especial: 'escudo', stats: { danoRecebido: 0.9 } }, ['terra', 'capa']],
  ['rel_elfa', 'Flecha Élfica', 'A cada 6 tiros: uma flecha que atravessa tudo.', 'pena', '#7fdc8a', 2,
    { gatilhos: [{ quando: 'tiro', cada: 6, efeitos: [['leque', { n: 1, abertura: 0, dano: 6, perfura: 99, tex: 'agulha', cor: '#7fdc8a', vel: 420 }]] }] }, ['lamina', 'olhar']],
  ['teclado_criador', 'Teclado do Criador', 'A cada 15 tiros, aperta uma tecla aleatória: um efeito surpresa (explosão, raios, meteoros, lâminas...).', 'cubo', '#7fdc8a', 3,
    { gatilhos: [{ quando: 'tiro', cada: 15, efeitos: [['aleatorio', {}]] }] }, ['eco', 'sorte']],
  ['rel_mago', 'Grimório', 'Seu item ativo carrega 2 por sala limpa.', 'livro', '#c86bff', 3,
    { passivos: ['grimorio'] }, ['tempo', 'pergaminho']],
];
